CHROMIUM: Allow building cros_ec without internal
Allow flashrom to build with only the minimum possible set
of code paths for the purposes of cros_ec legacy users.
Specifically FP team who want to use a frozen flashrom version
as their backend for some time.

NOTE: meson.build diff with upstream intentionally unordered
to mitigate Copybot conflicts.

BUG=b:138782393,b:296978620
BRANCH=none
TEST=`$ meson -Dprogrammer="dummy" -Ddefault_programmer_name=cros_ec -Ddefault_programmer_args="type=fp" -Dtests=disabled ../ && ninja`.
TEST=`$ nm flashrom | grep cros_ec`.
TEST=`$ ./flashrom
flashrom 1.4.0-devel on Linux 6.3.11-1rodete1-amd64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
         >> The fp subtype is deprecated! Remove call site NOW as this WILL be deleted! <<

Error: Programmer initialization failed.
```.

Signed-off-by: Edward O'Callaghan <quasisec@google.com>
Change-Id: I6d2d53a9d0ecfb4198e383d5675ec4de2b18297f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/4798070
Auto-Submit: Edward O'Callaghan <quasisec@chromium.org>
Tested-by: Edward O'Callaghan <quasisec@chromium.org>
Commit-Queue: Edward O'Callaghan <quasisec@chromium.org>
Reviewed-by: Craig Hesling <hesling@chromium.org>
Commit-Queue: Craig Hesling <hesling@chromium.org>
Reviewed-by: Sam McNally <sammc@chromium.org>